#!/usr/bin/env python3
"""
Symmetric ansatz for the window CNF: WR(n, k) without normalisation, restricted to event
orders that are invariant under a group generated by maps of two kinds,

    rot:CYCLES:A:S    (v, r) -> (g v, r + S)     order preserving,
    rev:CYCLES:A:C    (v, r) -> (g v, C - r)     order reversing (time reversal),

where g(v) = p(v) XOR A, p permutes coordinates (cycles separated by '/', e.g. 0123/45,
or '-'), and A is a bit mask (e.g. 0000011, or '-').

Such a restriction is only good for *finding* representants: a satisfying assignment of the
restricted CNF satisfies WR(n, k) (every WR clause is kept), so it glues (section 6a) to a
genuine event order in which all edges alternate and no pair at distance 2 or 3 alternates.
An unsatisfiable ansatz proves nothing about WR(n, k) itself.

Which groups can occur.  An order automorphism of the event order that fixes every rank is
the identity (it shifts all positions by the same amount, and so does its m-th power, which is
the identity on vertices).  Hence the symmetry group of a representant maps injectively to the
group of rank maps r -> +-r + c modulo 2k, the dihedral group of order 4k; in particular an
order-preserving symmetry (g, S) needs ord(g) * S = 0 mod 2k with no smaller power of g
fixing all vertices while shifting ranks by a multiple of 2k, and every order-reversing
symmetry is an involution on vertices.  `check_faithful` verifies this for the generated
group before the CNF is written (an unfaithful group gives an ansatz that is trivially
unsatisfiable).

Usage: python3 symmetric_ansatz.py N K OUT.cnf GEN [GEN ...]
"""
import sys

from event_cnf import popcount
from window_cnf import WindowCNF


def parse(n, spec):
    kind, cyc, a, t = spec.split(":")
    p = list(range(n))
    if cyc not in ("-", ""):
        for cy in cyc.split("/"):
            c = [int(x) for x in cy]
            for i in range(len(c)):
                p[c[i]] = c[(i + 1) % len(c)]
    a = int(a, 2) if a not in ("-", "") else 0
    g = tuple(sum(1 << p[i] for i in range(n) if v >> i & 1) ^ a for v in range(1 << n))
    return kind, g, int(t)


def check_faithful(n, k, gens):
    """closure of the generators as (vertex map, orientation, shift); the kernel of the
    projection to rank maps must be trivial"""
    P, ident = 2 * k, tuple(range(1 << n))
    el = [(g, 1 if kind == "rot" else -1, t % P) for kind, g, t in gens]
    G, frontier = {(ident, 1, 0)}, [(ident, 1, 0)]
    while frontier:
        new = []
        for f, o, s in frontier:
            for g, o2, s2 in el:
                z = (tuple(g[f[v]] for v in range(1 << n)), o2 * o, (o2 * s + s2) % P)
                if z not in G:
                    G.add(z)
                    new.append(z)
        frontier = new
    bad = [x for x in G if x[1] == 1 and x[2] == 0 and x[0] != ident]
    shifts = sorted(x[2] for x in G if x[1] == 1 and x[0] == ident and x[2])
    return len(G), not bad, shifts


def build(n, k, gens):
    for kind, g, t in gens:
        for v in range(1 << n):
            d = popcount(g[v]) - popcount(v) - t if kind == "rot" else popcount(g[v]) + popcount(v) - t
            assert d % 2 == 0, "the map does not respect rank parity"
    E = WindowCNF(n, k)
    E.shortest = False
    E.windows()
    E.nonalt()
    for key, v in list(E.var.items()):
        if key[0] != "lt":
            continue
        _, a, r, b, s = key
        for kind, g, t in gens:
            img = E.before(g[a], r + t, g[b], s + t) if kind == "rot" else E.before(g[b], t - s, g[a], t - r)
            if isinstance(img, bool):
                E.add([v] if img else [-v])
            else:
                E.add([-v, img])
                E.add([v, -img])
    return E


if __name__ == "__main__":
    n, k, out = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
    gens = [parse(n, s) for s in sys.argv[4:]]
    order, ok, shifts = check_faithful(n, k, gens)
    if not ok:
        sys.exit(f"group of order {order} does not act faithfully on ranks: not a valid ansatz")
    if shifts:
        # invariance under (v, r) -> (v, r + s) makes the word a power of a shorter word
        print(f"note: the group contains the pure rank shifts {shifts}; the ansatz only finds words "
              f"that are powers of a {min(shifts) // 2}-uniform word")
    E = build(n, k, gens)
    E.write(out)
    print(f"group order {order}: {len(E.var)} variables, {len(E.clauses)} clauses -> {out}")
